remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "assets/css/skins/light.css"

# Site Settings
locale                   : "en"
title                    : "corey-lehmann.github.io"
description              : "" 
url                      : "https://corey-lehmann.github.io/"
mathjax: true

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Site Author
author:
  name             : "Corey Lehmann"
  picture          : "\assets\images\HappyOtter.jpg"
  email            : "clehmann10@gmail.com"
  links:
  - title: GitHub
    url: https://github.com/corey-lehmann
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/coreylehmann/
    icon: fab fa-linkedin

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/corey-lehmann
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/coreylehmann/
    icon: fab fa-linkedin
  - title: Kaggle
    url: https://www.kaggle.com/clehmann10
    icon: fa fa-bar-chart